/**
 * Deterministic Demo / Mock Repository for Indian Standards & BIS Services.
 *
 * IMPORTANT NOTICE:
 * All records in this file are simulated DEMO/TEST records for SIH 2026 PS107 evaluation.
 * They are clearly flagged with isDemoRecord: true and are NOT live official BIS data.
 */

import type { BisStandardDetail, LicenseVerificationResult, QualityControlOrderItem } from './types'

export const DEMO_STANDARDS: BisStandardDetail[] = [
  {
    id: 'demo-std-is-10500-2012',
    standardNumber: 'IS 10500:2012',
    title: 'Drinking Water — Specification (Second Revision) [DEMO TEST RECORD]',
    description:
      'Prescribes the requirements and methods of sampling and test for drinking water suitable for human consumption.',
    edition: 'Second Revision',
    year: 2012,
    status: 'ACTIVE',
    division: 'FAD',
    icsCode: '13.060.20',
    isMandatory: true,
    mandatedByQco: 'Drinking Water Quality Control Mandate',
    clausesCount: 5,
    createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    clauses: [
      {
        id: 'demo-clause-10500-4-1',
        standardId: 'demo-std-is-10500-2012',
        clauseNumber: '4.1',
        title: 'Organoleptic and Physical Parameters (Table 1)',
        content:
          'Drinking water shall comply with the organoleptic and physical parameters specified in Table 1: Color max 5 Hazen units, Odour Agreeable, pH value 6.5 to 8.5, Turbidity max 1 NTU, Total dissolved solids (TDS) max 500 mg/l.',
        isMandatory: true,
        clauseType: 'SPECIFICATION',
        limits: [
          { parameter: 'pH value', requirement: '6.5 - 8.5', unit: 'pH' },
          { parameter: 'Turbidity', requirement: 'Max 1.0', unit: 'NTU' },
          { parameter: 'Total Dissolved Solids (TDS)', requirement: 'Max 500', unit: 'mg/l' },
        ],
        orderIndex: 1,
      },
      {
        id: 'demo-clause-10500-4-2',
        standardId: 'demo-std-is-10500-2012',
        clauseNumber: '4.2',
        title: 'General Chemical Parameters (Table 2)',
        content:
          'Parameters concerning substances undesirable in excessive amounts: Total hardness (as CaCO3) max 200 mg/l, Iron (as Fe) max 1.0 mg/l, Chlorides (as Cl) max 250 mg/l, Fluoride (as F) max 1.0 mg/l.',
        isMandatory: true,
        clauseType: 'SPECIFICATION',
        limits: [
          { parameter: 'Total Hardness', requirement: 'Max 200', unit: 'mg/l' },
          { parameter: 'Chlorides', requirement: 'Max 250', unit: 'mg/l' },
          { parameter: 'Fluoride', requirement: 'Max 1.0', unit: 'mg/l' },
        ],
        orderIndex: 2,
      },
      {
        id: 'demo-clause-10500-4-3',
        standardId: 'demo-std-is-10500-2012',
        clauseNumber: '4.3',
        title: 'Toxic Substances Parameters (Table 3)',
        content:
          'Parameters concerning toxic substances: Lead (as Pb) max 0.01 mg/l, Arsenic (as As) max 0.01 mg/l, Total Mercury (as Hg) max 0.001 mg/l, Cadmium (as Cd) max 0.003 mg/l.',
        isMandatory: true,
        clauseType: 'SAFETY_REQUIREMENT',
        limits: [
          { parameter: 'Lead (Pb)', requirement: 'Max 0.01', unit: 'mg/l' },
          { parameter: 'Arsenic (As)', requirement: 'Max 0.01', unit: 'mg/l' },
          { parameter: 'Mercury (Hg)', requirement: 'Max 0.001', unit: 'mg/l' },
        ],
        orderIndex: 3,
      },
      {
        id: 'demo-clause-10500-4-4',
        standardId: 'demo-std-is-10500-2012',
        clauseNumber: '4.4',
        title: 'Bacteriological Parameters (Table 4)',
        content:
          'All samples of drinking water shall be free from coliform organisms and E. coli. E. coli or thermotolerant coliform bacteria shall not be detectable in any 100 ml sample.',
        isMandatory: true,
        clauseType: 'SAFETY_REQUIREMENT',
        limits: [
          { parameter: 'E. coli', requirement: 'Shall not be detectable in 100 ml', unit: 'CFU/100ml' },
        ],
        orderIndex: 4,
      },
      {
        id: 'demo-clause-10500-5-1',
        standardId: 'demo-std-is-10500-2012',
        clauseNumber: '5.1',
        title: 'Marking and Conformance',
        content:
          'Containers and packages shall be marked with the statement: "Conforms to IS 10500:2012" and shall bear the Standard Mark (ISI mark) under a valid certification license granted by the Bureau of Indian Standards.',
        isMandatory: true,
        clauseType: 'PACKAGING_MARKING',
        orderIndex: 5,
      },
    ],
  },
  {
    id: 'demo-std-is-1293-2019',
    standardNumber: 'IS 1293:2019',
    title:
      'Plugs and Socket-Outlets for Household and Similar Purposes of Rated Voltage up to and Including 250 V and Rated Current up to and Including 16 A — Specification [DEMO TEST RECORD]',
    description:
      'Applies to plugs and fixed or portable socket-outlets for a.c. only, with or without earthing contact, with a rated voltage up to and including 250 V and a rated current up to and including 16 A.',
    edition: 'Fourth Revision',
    year: 2019,
    status: 'ACTIVE',
    division: 'ETD',
    icsCode: '29.120.30',
    isMandatory: true,
    mandatedByQco: 'Plugs and Socket-Outlets (Quality Control) Order, 2021',
    clausesCount: 3,
    createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    clauses: [
      {
        id: 'demo-clause-1293-6-1',
        standardId: 'demo-std-is-1293-2019',
        clauseNumber: '6.1',
        title: 'Standard Ratings',
        content:
          'Standard rated currents are 2.5 A, 6 A, and 16 A at rated voltage of 250 V. Plugs of 10 A rating are non-standard and strictly disallowed.',
        isMandatory: true,
        clauseType: 'SPECIFICATION',
        orderIndex: 1,
      },
      {
        id: 'demo-clause-1293-8-1',
        standardId: 'demo-std-is-1293-2019',
        clauseNumber: '8.1',
        title: 'Marking',
        content:
          'Accessories shall be marked with rated current in amperes, rated voltage in volts, nature of supply, manufacturer name or registered trademark, and the Standard Mark (ISI mark) with CM/L number.',
        isMandatory: true,
        clauseType: 'PACKAGING_MARKING',
        orderIndex: 2,
      },
      {
        id: 'demo-clause-1293-13-1',
        standardId: 'demo-std-is-1293-2019',
        clauseNumber: '13.1',
        title: 'Resistance to Electric Shock and Heat',
        content:
          'Plugs and socket-outlets shall be designed so that live parts are not accessible when the plug is in partial or complete engagement.',
        isMandatory: true,
        clauseType: 'SAFETY_REQUIREMENT',
        orderIndex: 3,
      },
    ],
  },
  {
    id: 'demo-std-is-9873-1-2019',
    standardNumber: 'IS 9873 (Part 1):2019',
    title: 'Safety of Toys — Part 1: Safety Aspects Related to Mechanical and Physical Properties [DEMO TEST RECORD]',
    description:
      'Specifies acceptable criteria for structural and mechanical characteristics of toys, including shape, size, contour, and spacing.',
    edition: 'Third Revision',
    year: 2019,
    status: 'ACTIVE',
    division: 'PCD',
    icsCode: '97.190',
    isMandatory: true,
    mandatedByQco: 'Toys (Quality Control) Order, 2020',
    clausesCount: 2,
    createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    clauses: [
      {
        id: 'demo-clause-9873-4-2',
        standardId: 'demo-std-is-9873-1-2019',
        clauseNumber: '4.2',
        title: 'Small Parts Hazards',
        content:
          'Toys intended for children under 36 months of age, and their component parts, shall not fit entirely into the small parts cylinder when tested under mechanical abuse force of 50 N.',
        isMandatory: true,
        clauseType: 'SAFETY_REQUIREMENT',
        orderIndex: 1,
      },
      {
        id: 'demo-clause-9873-7-1',
        standardId: 'demo-std-is-9873-1-2019',
        clauseNumber: '7.1',
        title: 'Mandatory Marking and Age Warning',
        content:
          'Toys shall bear the Standard Mark (ISI mark) under Scheme-I along with the CM/L license number and applicable age suitability warnings (e.g. "Not suitable for children under 3 years due to small parts").',
        isMandatory: true,
        clauseType: 'PACKAGING_MARKING',
        orderIndex: 2,
      },
    ],
  },
  {
    id: 'demo-std-is-13252-1-2010',
    standardNumber: 'IS 13252 (Part 1):2010',
    title: 'Information Technology Equipment — Safety — Part 1: General Requirements [DEMO TEST RECORD]',
    description:
      'Applicable to mains-powered or battery-powered information technology equipment, including power adapters and laptops.',
    edition: 'First Revision',
    year: 2010,
    status: 'ACTIVE',
    division: 'LITD',
    icsCode: '35.020',
    isMandatory: true,
    mandatedByQco: 'Electronics and Information Technology Goods (Requirement for Compulsory Registration) Order',
    clausesCount: 2,
    createdAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    updatedAt: new Date('2024-01-01T00:00:00.000Z').toISOString(),
    clauses: [
      {
        id: 'demo-clause-13252-1-7',
        standardId: 'demo-std-is-13252-1-2010',
        clauseNumber: '1.7',
        title: 'Marking and Identification under CRS',
        content:
          'Equipment shall be marked with the standard self-declaration mark reading "Self-Declaration - Conforming to IS 13252 (Part 1):2010", the 8-digit registration number "R-XXXXXXXX", and reference portal "www.crsbis.in".',
        isMandatory: true,
        clauseType: 'PACKAGING_MARKING',
        orderIndex: 1,
      },
      {
        id: 'demo-clause-13252-2-1',
        standardId: 'demo-std-is-13252-1-2010',
        clauseNumber: '2.1',
        title: 'Protection from Electric Shock and Energy Hazards',
        content:
          'Accessible parts shall not be hazardous live parts. Creepage distances and electrical clearances must satisfy Table 2H under tropical operating environments.',
        isMandatory: true,
        clauseType: 'SAFETY_REQUIREMENT',
        orderIndex: 2,
      },
    ],
  },
]

export const DEMO_LICENSES: LicenseVerificationResult[] = [
  {
    isValid: true,
    status: 'OPERATIVE',
    licenseType: 'ISI_CML',
    licenseNumber: 'CM/L-8400123',
    standardNumber: 'IS 10500:2012',
    licenseeName: 'Himalayan Springs Water Pvt Ltd [DEMO TEST RECORD]',
    brandName: 'AquaPure Demo',
    factoryAddress: 'Plot 12, Industrial Area, Solan, Himachal Pradesh - 173212, India',
    validFrom: '2023-01-01T00:00:00.000Z',
    validUntil: '2027-12-31T23:59:59.000Z',
    productCategory: 'Drinking Water',
    varietyDescription: 'Packaged Natural Drinking Water in PET bottles (500ml, 1000ml)',
    details: {
      scheme: 'Scheme-I (ISI Certification)',
      supervisingBranch: 'Chandigarh Branch Office (CBO)',
    },
    isDemoRecord: true,
    message: 'Valid and Operative ISI Certification Marks License (CM/L-8400123) under IS 10500:2012 [DEMO RECORD].',
  },
  {
    isValid: false,
    status: 'EXPIRED',
    licenseType: 'ISI_CML',
    licenseNumber: 'CM/L-7123456',
    standardNumber: 'IS 1293:2019',
    licenseeName: 'National Spark Plugs & Cables Ltd [DEMO TEST RECORD]',
    brandName: 'PowerSpark Demo',
    factoryAddress: 'Sector 5, IMT Manesar, Gurugram, Haryana - 122050, India',
    validFrom: '2020-04-01T00:00:00.000Z',
    validUntil: '2023-03-31T23:59:59.000Z',
    productCategory: 'Plugs and Socket-Outlets',
    varietyDescription: '16A 250V 3-Pin Rewireable Plugs',
    details: {
      scheme: 'Scheme-I (ISI Certification)',
      supervisingBranch: 'Delhi Branch Office-I',
    },
    isDemoRecord: true,
    message: 'Caution: This ISI License (CM/L-7123456) expired on 31-Mar-2023 and is no longer operative [DEMO RECORD].',
  },
  {
    isValid: true,
    status: 'OPERATIVE',
    licenseType: 'CRS_REGISTRATION',
    licenseNumber: 'R-41009876',
    standardNumber: 'IS 13252 (Part 1):2010',
    licenseeName: 'Apex Electronics Global Corp [DEMO TEST RECORD]',
    brandName: 'ApexPower Demo',
    factoryAddress: 'Shenzhen Industrial Park (Indian Representative: Apex India Corp, New Delhi)',
    validFrom: '2022-06-15T00:00:00.000Z',
    validUntil: '2026-06-14T23:59:59.000Z',
    productCategory: 'Power Adaptors for IT Equipment',
    varietyDescription: 'Switching Mode Power Adaptor 65W USB-C',
    details: {
      scheme: 'Scheme-II (Compulsory Registration Scheme - CRS)',
      registeredModels: ['AP-65W-USB-C', 'AP-45W-FAST', 'AP-100W-PRO'],
      testReportRef: 'TEST-NABL-2022-8921',
    },
    isDemoRecord: true,
    message: 'Valid Operative BIS Compulsory Registration (R-41009876) under IS 13252 (Part 1):2010 [DEMO RECORD].',
  },
  {
    isValid: true,
    status: 'OPERATIVE',
    licenseType: 'HALLMARK_HUID',
    licenseNumber: 'HUID:AB12CD',
    standardNumber: 'IS 1417:2016',
    licenseeName: 'Tanishq Jewellers Franchise [DEMO TEST RECORD]',
    brandName: 'Tanishq Demo',
    productCategory: 'Gold Jewellery 22K (916)',
    validFrom: '2024-01-01T00:00:00.000Z',
    validUntil: null,
    details: {
      purityPpm: 916,
      purityKarat: '22 Karat',
      articleType: 'Gold Bangle',
      grossWeightGrams: 14.85,
      assayingCenter: 'Assaying & Hallmarking Centre Delhi (AHC-DL-04)',
      hallmarkedDate: '2024-02-14',
    },
    isDemoRecord: true,
    message: 'Authentic 6-character HUID (AB12CD) verified for 22K 916 Gold Jewellery [DEMO RECORD].',
  },
]

export const DEMO_QCOS: QualityControlOrderItem[] = [
  {
    id: 'demo-qco-toys-2020',
    orderTitle: 'Toys (Quality Control) Order, 2020 [DEMO/OFFICIAL REF]',
    orderNumber: 'S.O. 853(E)',
    ministry: 'Ministry of Commerce and Industry (DPIIT)',
    notifiedDate: '2020-02-25T00:00:00.000Z',
    effectiveDate: '2021-01-01T00:00:00.000Z',
    status: 'IN_FORCE',
    standardNumber: 'IS 9873 (Part 1):2019',
    applicableProducts: 'Toys intended for use in play by children under 14 years of age.',
    hsCodes: ['950300', '95030010', '95030020', '95030030', '95030090'],
    isExemptionApplicable: true,
    exemptionDetails: 'Goods or articles manufactured in India solely for export are exempt.',
    gazetteUrl: 'https://dpiit.gov.in/sites/default/files/Toys_QCO_2020.pdf',
    isDemoRecord: true,
  },
  {
    id: 'demo-qco-plugs-2021',
    orderTitle: 'Plugs and Socket-Outlets (Quality Control) Order, 2021 [DEMO/OFFICIAL REF]',
    orderNumber: 'S.O. 3673(E)',
    ministry: 'Ministry of Heavy Industries',
    notifiedDate: '2021-09-03T00:00:00.000Z',
    effectiveDate: '2022-03-01T00:00:00.000Z',
    status: 'IN_FORCE',
    standardNumber: 'IS 1293:2019',
    applicableProducts: 'Plugs and socket-outlets for rated voltages up to 250V and rated current up to 16A.',
    hsCodes: ['853669', '85366910', '85366990'],
    isExemptionApplicable: false,
    exemptionDetails: null,
    gazetteUrl: 'https://heavyindustries.gov.in/qco-plugs-2021.pdf',
    isDemoRecord: true,
  },
]
